#!/usr/bin/env bash

ipaddr="172.17.0.2"
port="9042"
container="cluster"

# get articles
docker exec  $container cqlsh -k "bde" -e "select entry_url, reversed_host from news_articles" | head -n -2 | tail -n +4  \
| sed "s<[ ]|[ ]<' and reversed_host='<g" \
| sed "s<http://<update news_articles set place_literal=null where entry_url='http://<g" \
| sed "s<$<';<g" | sed "s<^[ ][ ]*<<g"> del_location_cmds

cp del_location_cmds mnt/del_location_cmds
docker exec $container cqlsh -k "bde" -f /mnt/del_location_cmds
docker exec $container cqlsh -k "bde" -e "truncate location_extraction_log";
docker exec $container cqlsh -k "bde" -e "truncate news_articles_per_place";